
import "@/app/globals.css";
import type { Metadata } from "next";
import { SanityLive } from "./lib/live";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" suppressHydrationWarning>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/hcw1xut.css" />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
        <SanityLive />
      </body>
    </html>
  );
}
