
import "@/app/globals.css";
import type { Metadata } from "next";
import { SanityLive } from "./lib/live";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it" suppressHydrationWarning>
      <body>
        {children}
          <SanityLive />
      </body>
    </html>
  );
}
